# Dockerfile

# Step 1: Use an appropriate Node.js image
FROM node:20.16.0-alpine

# Step 2: Set the working directory
WORKDIR /app

# Step 3: Copy the package.json and package-lock.json (if you have one)
COPY package.json ./
COPY pnpm-lock.yaml ./

# Step 4: Install the dependencies
RUN npm install

# Step 5: Copy the rest of your application code
COPY . .

# Step 6: Run Prisma generate
RUN npx prisma generate

# Step 7: Build the application
RUN npm run build

# Step 8: Expose the port the app runs on
EXPOSE 8088

# Step 9: Start the application
CMD ["npm", "run", "start"]
