/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export interface HelloService {
    sayHello(
        data: HelloRequest,
        metadata?: Metadata,
        ...rest: any[]
    ): Observable<HelloResponse>;
}
export interface HelloRequest {
    name?: string;
}
export interface HelloResponse {
    message?: string;
}

