/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace sms {
    export interface HeroesService {
        findOne(
            data: HeroById,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Hero>;
    }
    export interface HeroById {
        id?: number;
    }
    export interface Hero {
        id?: number;
        name?: string;
    }
    export interface SmsService {
        hello(
            data: HelloRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<HelloResponse>;
        findOne(
            data: HeroById,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Hero>;
    }
    export interface HelloRequest {
        name?: string;
    }
    export interface HelloResponse {
        message?: string;
    }
}

