package main

import (
	"local_packages/api"
	"local_packages/database"

	"github.com/jackc/pgx/v4/pgxpool"
	gorm "gorm.io/gorm"

	"github.com/gin-gonic/gin"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware
)

func main() {
	var gorm *gorm.DB
	var dbpool *pgxpool.Pool
	dbpool, gorm = database.InitDB()
	svc := api.NewService(dbpool, gorm)

	router := gin.Default()
	api.SetupRoutes(router, svc)


	
    // URL to the Swagger JSON (it's generated by swag init command)
    swaggerURL := ginSwagger.URL("http://localhost:8080/swagger/doc.json")
    router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, swaggerURL))

	router.Run()
}




